name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python pillow
    
    - name: Verify files
      run: |
        echo "Repository contents:"
        ls -la
        echo "Checking spec file:"
        cat watermark_selector.spec
    
    - name: Build Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        echo "Building for Windows..."
        dir
        pyinstaller watermark_selector.spec
        dir dist
        cd dist
        7z a watermark-selector-windows.zip "视频水印区域选择工具.exe"
    
    - name: Build macOS
      if: matrix.os == 'macos-latest'
      run: |
        echo "Building for macOS..."
        ls -la
        pyinstaller watermark_selector.spec
        ls -la dist
        cd dist
        zip -r watermark-selector-mac.zip "视频水印区域选择工具.app"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/watermark-selector-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 