name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install opencv-python
        pip install pillow
        pip list
    
    - name: Check environment
      run: |
        echo "Current directory:"
        pwd
        echo "\nDirectory contents:"
        ls -la
        echo "\nPython version:"
        python --version
        echo "\nPyInstaller version:"
        pyinstaller --version
        echo "\nChecking Python files:"
        cat main.py
        echo "\nChecking imports:"
        python -c "import cv2; import tkinter; print('All imports successful')"
    
    - name: Build App
      run: |
        echo "Starting build process..."
        pyinstaller --name "视频水印区域选择工具" --windowed main.py --debug all
        echo "\nChecking dist directory:"
        ls -la dist
        echo "\nChecking build logs:"
        cat build/视频水印区域选择工具/*.log || echo "No log file found"
        echo "\nCreating zip file:"
        cd dist
        zip -r watermark-selector-mac.zip "视频水印区域选择工具.app"
        ls -la
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/watermark-selector-mac.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 